pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: Testing CSS and JavaScript
            image: node:15
            caches:
              - node
            script:
              - npm install
              - npm run stylelint
              - npm run lint
              - npm run tsc
              - npm run test
        - step:
            name: Testing PHP
            image: php:8-fpm
            caches:
              - composer
            script:
              - apt-get clean
              - apt-get update
              - apt-get upgrade -y
              - apt-get install -y git
              - apt-get install -y libcurl4-openssl-dev
              - apt-get install -y libonig-dev
              - apt-get install -y libpng-dev
              - apt-get install -y libssl-dev
              - apt-get install -y libxml2-dev
              - apt-get install -y libzip-dev
              - apt-get install -y unzip
              - apt-get install -y wget
              - apt-get install -y zip
              - docker-php-ext-install bcmath
              - docker-php-ext-install ctype
              - docker-php-ext-install mbstring
              - docker-php-ext-install pdo_mysql
              - docker-php-ext-install tokenizer
              - docker-php-ext-install xml
              - docker-php-ext-install zip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - cp .env.example .env
              - echo "MARVEL_PUBLIC_API_KEY=$MARVEL_PUBLIC_API_KEY" >> .env
              - echo "MARVEL_PRIVATE_API_KEY=$MARVEL_PRIVATE_API_KEY" >> .env
              - php artisan key:generate
              - composer run lint
              - composer run phpcs
              - composer run phpstan
              - composer run test
