image: php:8-fpm

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build & Test
          caches:
            - composer
          script:
            - apt-get update && apt-get install -qy git # libonig-dev libxml2-dev libzip-dev unzip zip
            # - docker-php-ext-install bcmath ctype json mbstring pdo_mysql tokenizer xml zip
            # - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            # - composer install
            # - php artisan key:generate
            # - composer run lint
            # - composer run phpcs
            # - composer run phpstan
            # - php artisan optimize:clear
            # - php artisan serve &
            # - sleep 5
            # - composer run test
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
            - npm install
