image: php:8-fpm

pipelines:
  pull-requests:
    '**':
      - step:
          name: Build
          services:
            - docker
          caches:
            - docker
            - composer
            - node
          script:
            - apt-get clean
            - apt-get update
            - apt-get upgrade -y
            - apt-get install -y git
            - apt-get install -y libcurl4-openssl-dev
            - apt-get install -y libonig-dev
            - apt-get install -y libpng-dev
            - apt-get install -y libssl-dev
            - apt-get install -y libxml2-dev
            - apt-get install -y libzip-dev
            - apt-get install -y unzip
            - apt-get install -y wget
            - apt-get install -y zip
            - docker-php-ext-install bcmath
            - docker-php-ext-install ctype
            - docker-php-ext-install mbstring
            - docker-php-ext-install pdo_mysql
            - docker-php-ext-install tokenizer
            - docker-php-ext-install xml
            - docker-php-ext-install zip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - cp .env.example .env
            - php artisan key:generate
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
            - source ~/.bashrc
            - npm install
      - step:
          name: Testing CSS
          script:
            - npm run stylelint
      - step:
          name: Testing JavaScript
          script:
            - npm run lint
            - npm run tsc
            - npm run test
      - step:
          name: Testing PHP
          script:
            - composer run lint
            - composer run phpcs
            - composer run phpstan
            - php artisan optimize:clear
            - php artisan serve &
            - sleep 5
            - composer run test
