# https://docs.docker.com/compose/compose-file/#/versioning
version: '3'

services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: marvel_nginx
    build: ./docker/nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/vhost/:cached
    ports:
      - '80:80'
      - '443:443'
    networks:
      - docker_network

  php:
    # https://hub.docker.com/_/php
    container_name: marvel_php
    build: ./docker/php
    environment:
      PHP_MEMORY_LIMIT: '128M'
    volumes:
      - ./:/var/www/vhost/:cached
    ports:
      - '9000:9000'
    networks:
      - docker_network
  node:
    build:
      context: ./.docker/node
    container_name: marvel_node
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
