# https://docs.docker.com/compose/compose-file/#/versioning
version: '3'

services:
  nginx:
    # https://hub.docker.com/_/nginx
    container_name: marvel_nginx
    build: ./docker/nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    ports:
      - '80:80'
      - '443:443'
    networks:
      - docker_network

  php:
    # https://hub.docker.com/_/php
    container_name: marvel_php
    build: ./docker/php
    environment:
      PHP_MEMORY_LIMIT: '128M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    ports:
      - '9000:9000'
    networks:
      - docker_network

  node:
    container_name: marvel_node
    image: "node:15"
    user: "node"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www/vhost/:cached
    working_dir: /var/www/vhost/
    networks:
      - docker_network
    command: "npm install"

  mysql:
    container_name: marvel_mysql
    image: mysql/mysql-server:latest
    volumes:
      - ./mysql/data:/var/lib/mysql:cached
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marvel
      MYSQL_USER: marvel_user
      MYSQL_PASSWORD: jump24
      MYSQL_ROOT_HOST: '%'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - docker_network
    ports:
      - 4406:3306

networks:
  docker_network:
    driver: bridge
